baseURL: ""
relativeURLs: "True"
languageCode: "en-us"
title: "cd home\\oum's Portfolio"
theme: hugo-profile

Paginate: 1
googleAnalytics: G-G8R0Q0KB5E

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: 
#       weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: 
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "~$ echo Oumaima Mhiriz "
  description: 
  # staticPath: ""  # The path to serve the static files from


  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:
    textColor: "#1c1c1c"
    secondaryTextColor: "#292929"
    backgroundColor: "#f6f6f6"
    primaryColor: "#1c1c1c"
    secondaryColor: "#fff"

    darkmode:
      textColor: "#fff"
      secondaryTextColor: "#fff"
      backgroundColor: "#051121"
      secondaryBackgroundColor: ""
      primaryColor: "#fff"
      secondaryColor: "#081b33"

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there üòä, I am"
    title: "Oumaima ."
    subtitle: "I am a network and telecommunications engineering student and I love creating new things"
    image: "/Capture-removebg.png"
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/uc?export=download&id=1UD90uEsPJ70AqYYExPmD_s87Q-q_WWic"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/zmiamuo
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/oumaima-mhiriz/


  # About
  about:
    enable: true
    title: "About Me"
    image: "/about.png"
    content: |-
      I recently graduated with a Bachelor‚Äôs Degree in Applied Mathematics, and as the next step I want to pursue a Master‚Äôs Degree in the Data Science and Machine Learning field. I strongly believe that Machine Learning is the future, as it can be used to solve many of the complex problems we face in our daily life.
      
      I am currently taking the Data Science and Machine Learning courses from DataCamp to sharpen my skills and be better equipped for the upcoming challenges.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently :"
      items:
        - "Python"
        - "Pandas"
        - "Seaborn"
        - "Keras"
        - "TensorFlow"
        - "Django"

  # Experience
  experience:
    enable: true
    items:
      - job: "Data Science & Advanced Analytics | Virtual Experience Program"
        company: "BCG"
        companyUrl: "https://www.theforage.com/virtual-internships/prototype/Tcz8gTtprzAS4xSoK/Data%20Science%20&%20Analytics%20Virtual%20Experience%20Program"
        date: "July 2022"
        featuredLink:
          enable: true
          name: "üíª View Project"
          url: "https://github.com/Hamagistral/BCG-VirtualExperience"
        content: |
                Worked on helping PowerCO a gas and electricity company that supplies SME,
                diagnose the source of churning customers. 
                
                I did the following tasks : 
                - Business Understanding
                - EDA & Feature Engineering 
                - Model Building
                - Communicating results to the client
                
                Created a model based on Random Forest algorithm, that predicted the probability of a customer churning in the future. 
                Thanks to this predictive model, we optimized the company strategy of giving the 20% discounts to only 
                potential churning customers.
        badges:
          - "Python"
          - "Pandas"
          - "Numpy"
          - "Scikit-learn"

      - job: "Data Analytics | Virtual Experience Program"
        company: "Accenture"
        companyUrl: "https://www.theforage.com/virtual-internships/prototype/hzmoNKtzvAzXsEqx8/Data-Analytics-Virtual-Experience?ref=ayhfcqWE2smDTGihD"
        date: "July 2022"
        featuredLink:
          enable: true
          name: "üíª View Project"
          url: "https://github.com/Hamagistral/ACCENTURE-VirutalExperience"
        info:
          enable: true
          content: 

        content: |
          Worked on helping SocialBuzz a video sharing social media platform, to analyse
                  the massive amount of data they have generated to identify some useful insights
                  such as the top 5 most popular categories and the month with most posts.

          I did the following tasks : 
          - Project Understanding
          - Data cleaning & Modeling
          - Data Visualization & Storytelling
          - Presenting to the Client

        badges:
          - "Google Spreadsheet"
          - "Google Slides"


      - job: "Software Engineering | Virtual Experience Program"
        company: "Quantium"
        companyUrl: "https://www.theforage.com/virtual-internships/prototype/jhiG2W9K8KLZK8nXP/Quantium:-Software-Engineering-Virtual-Experience-Program"
        date: "July 2022"
        featuredLink:
          enable: true
          name: "üíª View Project"
          url: "https://github.com/Hamagistral/Quantium-VirtualExperience"
        content: |
          Created a Dash Application to help Sould Foods, a food company, figure out if the sales were higher before or after the Pink Morsel price increase on the 15th of January, 2021. 

          I did the following tasks : 
          - Data Processing
          - Created a Dash Application
          - Improved the Dash visuals
          - Tested the Dash Application

        badges:
          - "Python"
          - "Pandas"
          - "Dash"
          - "CSS"
          - "Pytest"
          - "Selenium"

      - job: "Software Engineering | Virtual Experience Program"
        company: "JP Morgan"
        companyUrl: "https://www.theforage.com/virtual-internships/prototype/R5iK7HMxJGBgaSbvk/JP-Morgan-Banking-Technology-Virtual-Program?ref=ayhfcqWE2smDTGihD"
        date: "July 2022"
        featuredLink:
          enable: true
          name: "üíª View Project"
          url: "https://github.com/Hamagistral/JPMorgan-VirutalExperience"
        content: |
          Created an interface  with a stock price data feed data that is used by traders to identify under/over-valued stocks, using python, react and typescript.

          I did the following tasks : 
          - Creating the Interface with a stock price data feed
          - Used JPMorgan Chase frameworks and tools
          - Use Perspective (an internal tool) to create the chart for the trader‚Äôs dashboard

        badges:
          - "Python"
          - "React"
          - "Typescript"
          - "Financial Analysis"


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Science in Applied Mathematics"
        school:
          name: "Faculty of Sciences and Techniques of Mohammedia"
          url: "https://www.fstm.ac.ma/"
        date: "2019 - 2022"
        content: |-

          > üìö Related courses \: 

          ---

          > **üíª Computer science \:**
          > Programming with C ‚Ä¢
          > Data structures and Algorithms with C ‚Ä¢
          > Databases SQL

          > **üßÆ Mathematics \:**
          > Linear Algebra 
          > ‚Ä¢ Calculus
          > ‚Ä¢ Discrete Mathematics 
          > ‚Ä¢ Arithmetic & Cyrptography
          > ‚Ä¢ Probability & Markov Chains
          > ‚Ä¢ Statistics (Used R)
          > ‚Ä¢ Operational research and Optimization 
          > ‚Ä¢ Numerical Analysis 
          > ‚Ä¢ Scientific Computing 

          **üë®üèª‚Äçüíª Extracurricular Activities** : Member of  **[FSTM IT Club](https://www.linkedin.com/company/fstm-it-club/)**
     
      - title: "Baccalaureate in Physical Science"
        school:
          name: "Newton High School"
          url: "https://www.nischool.org/"
        date: "2018 - 2019"
        content: |-

          **üèÉüèª Extracurricular Activities** : 
          
            - üé• **Designer and Video Editer** for the School Football Club
            - ü•á **100m High School Sprint Record** 

  # Achievements
  achievements:
    enable: true
    items:
      - title: CS50 Web Programming
        content: Delivered by HARVARD
        technologies: HTML/CSS ‚Ä¢ JavaScript ‚Ä¢ Django
        url: https://certificates.cs50.io/12412c32-3309-47da-9176-0ca1a2bc353b.pdf?size=A4

      - title: Applied Data Science
        content: Delivered by IBM
        technologies: Python ‚Ä¢ Pandas ‚Ä¢ Numpy ‚Ä¢ Matplotlib
        url: https://www.credly.com/badges/03cfe5c6-bc59-49ab-a7a6-6acace81decf?source=linked_in_profile

      - title: Machine Learning
        content: Delivered by FreeCodeCamp
        technologies: Python ‚Ä¢ TensorFlow ‚Ä¢ Keras
        url: https://www.freecodecamp.org/certification/magistral/machine-learning-with-python-v7



  # projects
  projects:
    enable: true
    items:
      - title: Note Taking App For Students
        content: A full stack web application that allows students to take notes in the
                Cornell‚Äôs method, with an integrated video player to simplify the user experience,
                and implemented a ‚ÄùCalendar‚Äù feature which helps users track their exam and
                homework deadlines.
        image: studynotes.png
        featured:
          name: Video Demo
          link: https://www.youtube.com/watch?v=B4FXn7qWPaQ&ab_channel=HamzaElBelghiti
        badges:
          - "HTML"
          - "CSS"
          - "JavaScript"
          - "Django"
        links:
          - icon: fab fa-github
            url: https://github.com/zmiamuo/Studynotes


      - title: Simulating a virtual router search algorithms
        content: Created a price recommendation system based on the KNN algorithm to predict the
                ideal rental price for a new apartment listed in the Airbnb website, based on its features.
        image: airbnbpred.png
        featured:
          name: Notebook  
          link: https://colab.research.google.com/drive/19YtSRT4w89TjFMRATrrRVQv0r1a1S3Wj?usp=sharing
        badges:
          - "Python"
          - "Pandas"
          - "Numpy"
          - "Scikit-learn"
        links:
          - icon: fab fa-github
            url: https://github.com/zmiamuo

      - title: Stock Price Interface
        content: Created a stock price data feed interface used by traders to identify under/over-valued stocks.
        image: stock.png
        badges:
          -  Python
          -  React
          -  Typescript
        links:
          - icon: fab fa-github
            url: https://github.com/zmiamuo/

  #Contact
  contact:
    enable: true
    content: Thank you for visiting my portfolio üôèüèº ! Have any questions ? Feel free to contact me via **[Linkedin](https://www.linkedin.com/in/oumaima-mhiriz/)** or **Email** ‚¨áÔ∏è
    email: oumaimamhiriz@gmail.com
    btnName: üì® Email Me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/zmiamuo
      linkedin: https://www.linkedin.com/in/oumaima-mhiriz/